apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- was.yaml
resources:
- was.yaml
images:
- name: cicd-image
  newName: public.ecr.aws/f1s4m0n8/yong
  newTag: v10
namespace: default
