apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- was.yaml
resources:
- was.yaml
images:
- name: cicd-image
  newName: yonggyucho/rapa-cicdlab
  newTag: "3"
namespace: default
